//
//  DashboardProtocols.swift
//  VK Test Assignment
//
//  Created Nariman on 22.03.2024.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Dastan Makhutov @mchutov
//

import Foundation

//MARK: Wireframe -
protocol DashboardWireframeProtocol: AnyObject {
}
//MARK: Presenter -
protocol DashboardPresenterProtocol: AnyObject {
    func viewDidLoad()
    var entities: [[EntityViewModel]] { get set }
    var epidemicOverallStatistic: EpidemicOverallStatistic { get set }
    func select(at indexPath: IndexPath)
    func spreadInfection()
}

//MARK: Interactor -
protocol DashboardInteractorProtocol: AnyObject {
  var presenter: DashboardPresenterProtocol?  { get set }
}

//MARK: View -
protocol DashboardViewProtocol: AnyObject {
    var presenter: DashboardPresenterProtocol?  { get set }
    func configureStatisticsView(with model: EpidemicOverallStatistic)
    func update()
    func updateTimer(with text: String)
    func updateMainStatistic(uninfected: String, infected: String)
    func updateProgressView(_ progress: Float)
    func end(with model: SimulationEndModel)
}
