//
//  DashboardRouter.swift
//  VK Test Assignment
//
//  Created Nariman on 22.03.2024.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Dastan Makhutov @mchutov
//

import UIKit

final class DashboardRouter: DashboardWireframeProtocol {
    weak var viewController: UIViewController?
    
    static func createModule(
        with model: UserInputModel
    ) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = DashboardViewController()
        let interactor = DashboardInteractor()
        let router = DashboardRouter()
        let presenter = DashboardPresenter(
            interface: view,
            interactor: interactor,
            router: router,
            model: model
        )
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
