//
//  DataCollectionProtocols.swift
//  VK Test Assignment
//
//  Created Nariman on 22.03.2024.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Dastan Makhutov @mchutov
//

import Foundation

//MARK: Wireframe -
protocol DataCollectionWireframeProtocol: AnyObject {

}
//MARK: Presenter -
protocol DataCollectionPresenterProtocol: AnyObject {

}

//MARK: Interactor -
protocol DataCollectionInteractorProtocol: AnyObject {
  var presenter: DataCollectionPresenterProtocol?  { get set }
}

//MARK: View -
protocol DataCollectionViewProtocol: AnyObject {
  var presenter: DataCollectionPresenterProtocol?  { get set }
}
