//
//  DataCollectionPresenter.swift
//  VK Test Assignment
//
//  Created Nariman on 22.03.2024.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Dastan Makhutov @mchutov
//

import UIKit

final class DataCollectionPresenter: DataCollectionPresenterProtocol {
    weak private var view: DataCollectionViewProtocol?
    var interactor: DataCollectionInteractorProtocol?
    private let router: DataCollectionWireframeProtocol

    init(interface: DataCollectionViewProtocol, interactor: DataCollectionInteractorProtocol?, router: DataCollectionWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
}
